# Generated by Django 3.0.6 on 2020-06-05 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('grade', models.CharField(choices=[('9th', 'Freshman'), ('10th', 'Sophomore'), ('11th', 'Junior'), ('12th', 'Senior')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CandidateIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_rank', models.IntegerField()),
                ('candidate', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='practice.Candidate')),
                ('issue', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='practice.Issue')),
            ],
        ),
    ]
