# Generated by Django 3.0.6 on 2020-06-05 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateissue',
            name='candidate',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_issues', to='practice.Candidate'),
        ),
        migrations.AlterField(
            model_name='candidateissue',
            name='issue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='practice.Issue'),
        ),
    ]
