# Generated by Django 3.0.6 on 2020-06-08 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20200605_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='practice.Candidate'),
        ),
    ]
