# Generated by Django 3.0.6 on 2020-06-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_student_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
