# Generated by Django 3.0.6 on 2020-06-09 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_candidate_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vote',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='practice.Candidate')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='practice.Student')),
            ],
        ),
    ]
