# Generated by Django 3.0.6 on 2020-06-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_auto_20200609_0555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='student',
            new_name='scooby',
        ),
    ]
