# Generated by Django 3.0.6 on 2020-06-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_auto_20200609_0626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
